app/base/__init__.py
from flask import Blueprint

base_blueprint = Blueprint('base', __name__, template_folder='templates')

from app.base import routes

app/base/routes.py
from flask import flash, render_template
from app.base import base_blueprint


@base_blueprint.route('/faq')
def faq():
    return render_template('footer/faq.html', title='FAQ')


@base_blueprint.route('/policy_privacy')
def privacy_policy():
	return render_template('footer/privacy_policy.html', title='Privacy Policy')


@base_blueprint.route('/policy_refund')
def refund_policy():
	return render_template('footer/refund_policy.html', title='Refund Policy')


@base_blueprint.route('/use_terms')
def use_terms():
	return render_template('footer/use_terms.html', title='Use Terms')

app/base/templates/footer/_footer.html
<footer>
	<div style='height:3vh; display:flex; align-items:center; justify-content:center;'>
		
			<p class='text-muted small' style='margin: auto;'>Copyright &#xA9; 2021. All Rights Reserved</p>
		
	</div>
</footer>

app/base/templates/footer/_landing_footer.html
<footer>
	<div class='col-12 py-5' style='display:flex; flex-wrap:wrap; align-items:flex-start; justify-content:center;'>
		<div class='col-12 col-sm-6 col-lg-3'>
			<h2 style='font-weight:100; color:#6FB2FF;'> 
				About Us
			</h2>
			<a href='{{ url_for("construction.landing") }}' class='text-muted' style='margin:auto;'>
				The Story of WhoseDoctor
			</a><br>
			<a href='{{ url_for("construction.landing") }}' class='text-muted' style='margin:auto;'>
				Newsroom
			</a><br>
			<a href='{{ url_for("construction.landing") }}' class='text-muted' style='margin:auto;'>
				Our Investors
			</a><br>
		</div>

		<div class='col-12 col-sm-6 col-lg-3'>
			<h2 style='font-weight:100; color:#6FB2FF;'> 
				Support
			</h2>
			<a href='{{ url_for("base.faq") }}' class='text-muted' style='margin:auto;'>
				FAQ
			</a><br>
			<a href='{{ url_for("home.feedback") }}' class='text-muted' style='margin:auto;'>
				Contact Us
			</a><br>
			<a href='{{ url_for("base.use_terms") }}' class='text-muted' style='margin:auto;'>
				Use Terms
			</a><br>
			<a href='{{ url_for("base.privacy_policy") }}' class='text-muted' style='margin:auto;'>
				Privacy Policy
			</a><br>
			<a href='{{ url_for("base.refund_policy") }}' class='text-muted' style='margin:auto;'>
				Refund Policy
			</a><br>
		</div>

		<div class='col-12 col-sm-6 col-lg-3'>
      <h2 style='font-family:Montserrat,sans-serif; font-weight:900; color:rgb(255, 255, 255);'>
        whose<span style='font-weight:300; color:rgb(254, 125, 1)'>doctor</span>
      </h2>
			<a href='{{ url_for("construction.landing") }}' class='text-muted' style='margin:auto;'>
				Tele-health Consultation
			</a><br>
		</div>
	</div>


	<div class='py-5' style='display:flex; align-items:center; justify-content:center;'>
		<div class='col-12 text-center'>
			<p class='text-muted' style='margin:auto;'>Copyright &#xA9; 2021. All Rights Reserved</p>
		</div>
	</div>
</footer>

app/base/templates/footer/faq.html
{% extends 'base/dash_layout.html' %}


{% block content %}
<section id='' class='d-flex align-items-center position-relative vh-45 cover intro' 
		style='background-image:url("/static/uploads/app_img/bg001.jpeg"); 
						display:flex; align-items:center; justify-content:center;
						background-size: cover; 
						background-repeat: no-repeat; 
						background-position: center center; 
						background-attachment: fixed;'>
	<div class='container-fluid' style='min-height:45vh; 
			display:flex; align-items:center; justify-content:center;'>
		<div class='row text-center'>
			<div class='col-12'>
				<h2 style='font-family:Montserrat,sans-serif; font-weight:900; color:rgb(21, 31, 42);'>
					whose<span style='font-weight:300; color:rgb(254, 125, 1);'>doctor</span>
				</h2>
			</div>
			<div class='col-12'>
				<h1 class='jumbotron-fluid' style='color:#4a4a4a'>
					<h1 style='font-family:Roboto; font-weight:900; color:rgb(21, 31, 42);'>
						Frequently Asked Questions
					</h1>
				</h1>
			</div>
		</div>
	</div>
</section>

<section>
	<div class='accordion' id='accordionExample'>
		<div class='card'>
			<div class='card-header' id='headingOne'>
				<h2 class='mb-0'>
				<button type='button' class='btn btn-link' style='text-decoration:none;' 
						data-toggle='collapse' data-target='#collapseOne'>
					Who are your doctors & where are the clinics located ?
				</button>
				</h2>
			</div>
			<div id='collapseOne' class='collapse' aria-labelledby='headingOne' data-parent='#accordionExample'>
				<div class='card-body'>
					<div class='container'>
						<p>
							We have a list of registered  doctors and clinics located in various parts of Singapore. We are growing!
							<br>
							<br>
							Upon submission of your tele-consult request, our system will match you to the closest available doctor based on your submitted address.
						</p>
					</div>
				</div>
			</div>
		</div>
		<div class='card'>
			<div class='card-header' id='headingTwo'>
				<h2 class='mb-0'>
				<button type='button' class='btn btn-link collapsed' style='text-decoration:none;'
						data-toggle='collapse' data-target='#collapseTwo'>
					What is the estimated cost of your tele-consult? 
				</button>
				</h2>
			</div>
			<div id='collapseTwo' class='collapse show' aria-labelledby='headingTwo' data-parent='#accordionExample'>
				<div class='card-body'>
					<div class='container'>
						<p>
							Tele-consultation fee is $20, inclusive of electronic MC.
						</p>
					</div>
				</div>
			</div>
		</div>
		<div class='card'>
			<div class='card-header' id='headingThree'>
				<h2 class='mb-0'>
				<button type='button' class='btn btn-link collapsed' style='text-decoration:none;'
						data-toggle='collapse' data-target='#collapseThree'>
					What about the cost of medications?
				</button>
				</h2>
			</div>
			<div id='collapseThree' class='collapse' aria-labelledby='headingThree' data-parent='#accordionExample'>
				<div class='card-body'>
					<div class='container'>
						<p>
							Prescription cost varies depending on the outcome of the tele-consult & your medical condition. Currently, we are unable to deliver your medications. 
						</p>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
{% endblock %}


{% block scripts %}
	{{ super() }}
	<script>
	$(document).ready(function(){
		// Add minus icon for collapse element which is open by default
		$('.collapse.show').each(function(){
			$(this).prev('.card-header').find('.fa').addClass('fa-minus').removeClass('fa-plus');
		});
		// Toggle plus minus icon on show hide of collapse element
		$('.collapse').on('show.bs.collapse', function(){
			$(this).prev('.card-header').find('.fa').removeClass('fa-plus').addClass('fa-minus');
		}).on('hide.bs.collapse', function(){
			$(this).prev('.card-header').find('.fa').removeClass('fa-minus').addClass('fa-plus');
		});
	});
	</script>
{% endblock %}

app/base/templates/footer/privacy_policy.html
{% extends 'base/dash_layout.html' %}


{% block content %}
<section id='' class='d-flex align-items-center position-relative vh-45 cover intro' 
		style='background-image:url("/static/uploads/app_img/bg001.jpeg"); 
						display:flex; align-items:center; justify-content:center;
						background-size: cover; 
						background-repeat: no-repeat; 
						background-position: center center; 
						background-attachment: fixed;'>
	<div class='container-fluid' style='min-height:45vh; 
			display:flex; align-items:center; justify-content:center;'>
		<div class='row text-center'>
			<div class='col-12'>
				<h2 style='font-family:Montserrat,sans-serif; font-weight:900; color:rgb(21, 31, 42);'>
					whose<span style='font-weight:300; color:rgb(254, 125, 1);'>doctor</span>
				</h2>
			</div>
			<div class='col-12'>
				<h1 class='jumbotron-fluid' style='color:#4a4a4a'>
					<h1 style='font-family:Roboto; font-weight:900; color:rgb(21, 31, 42);'>
						Privacy Policy
					</h1>
				</h1>
			</div>
		</div>
	</div>
</section>

<section class='py-4' style='background:#FFFFFF;'>
	<div class='container-fluid' 
			style='min-height:45vh; display:flex; flex-wrap:wrap; align-items:center; justify-content:center;'>
		<div class='col-12 col-sm-12 col-lg-6 pt-2'>
			<h6 class='pt-2' style='font-family:Montserrat,sans-serif; font-weight:900; color:#000000;'>
				Privacy Policy
			</h6>
			<ul>
				<li style='color:grey;'>
					We may use "cookies", where a small data file is sent to your browser to store and track information about you when you enter our websites. The cookie is used to track information such as the number of users and their frequency of use, profiles of users and their preferred sites. While this cookie can tell us when you enter our sites and which pages you visit, it cannot read data off your hard disk. 
				</li>
				<li style='color:grey;'>
					You can choose to accept or decline cookies. Most web browsers automatically accept cookies, but you can usually modify your browser setting to decline cookies if you prefer. This may prevent you from taking full advantage of the website.
				</li>

				<li style='color:grey;'>
					If you provide us with personally identifiable data,<br>
						<span style='text-indent:50px;'> 
							a. We will NOT share your personal data with non-Government agencies and non-Public Healthcare Institutions, except where such entities have been authorised to carry out specific Government services.
						</span><br>
						<span style='text-indent:50px;'>
							b. For your convenience, we may also display to you data you had previously supplied us. This will speed up the transaction and save you the trouble of repeating previous submissions. Should the data be out-of-date, please supply us the latest data.
						</span>
				</li>

				<li style='color:grey;'>
					To safeguard your personal data, all electronic storage and transmission of personal data is secured with appropriate security technologies.
				</li>

				<li style='color:grey;'>
					Our website and app may contain links to other sites whose data protection and privacy practices may differ from ours. We are not responsible for the content and privacy practices of these other websites and encourage you to consult the privacy notices of those sites.
				</li>

				<li style='color:grey;'>
					By booking a tele-consultation call to the doctor, you agree to make available your Personal Data to the doctor and employee(s) of the same establishment.
				</li>
			</ul>
		</div>
	</div>
</section>
{% endblock %}

app/base/templates/footer/refund_policy.html
{% extends 'base/dash_layout.html' %}


{% block content %}
<section id='' class='d-flex align-items-center position-relative vh-45 cover intro' 
		style='background-image:url("/static/uploads/app_img/bg001.jpeg"); 
						display:flex; align-items:center; justify-content:center;
						background-size: cover; 
						background-repeat: no-repeat; 
						background-position: center center; 
						background-attachment: fixed;'>
	<div class='container-fluid' style='min-height:45vh; 
			display:flex; align-items:center; justify-content:center;'>
		<div class='row text-center'>
			<div class='col-12'>
				<h2 style='font-family:Montserrat,sans-serif; font-weight:900; color:rgb(21, 31, 42);'>
					whose<span style='font-weight:300; color:rgb(254, 125, 1);'>doctor</span>
				</h2>
			</div>
			<div class='col-12'>
				<h1 class='jumbotron-fluid' style='color:#4a4a4a'>
					<h1 style='font-family:Roboto; font-weight:900; color:rgb(21, 31, 42);'>
						Refund Policy
					</h1>
				</h1>
			</div>
		</div>
	</div>
</section>

<section class='py-4' style='background:#FFFFFF;'>
	<div class='container-fluid' 
			style='min-height:45vh; display:flex; flex-wrap:wrap; align-items:center; justify-content:center;'>
		<div class='col-12 col-sm-12 col-lg-6 pt-2'>
			<h6 class='pt-2' style='font-family:Montserrat,sans-serif; font-weight:900; color:#000000;'>
				Refund Policy
			</h6>
			<ul>
				<li style='color:grey;'>
					Payment is non-refundable. 
				</li>
			</ul>
		</div>
	</div>
</section>
{% endblock %}

app/base/templates/footer/use_terms.html
{% extends 'base/dash_layout.html' %}


{% block content %}
<section id='' class='d-flex align-items-center position-relative vh-45 cover intro' 
		style='background-image:url("/static/uploads/app_img/bg001.jpeg"); 
						display:flex; align-items:center; justify-content:center;
						background-size: cover; 
						background-repeat: no-repeat; 
						background-position: center center; 
						background-attachment: fixed;'>
	<div class='container-fluid' style='min-height:45vh; 
			display:flex; align-items:center; justify-content:center;'>
		<div class='row text-center'>
			<div class='col-12'>
				<h2 style='font-family:Montserrat,sans-serif; font-weight:900; color:rgb(21, 31, 42);'>
					whose<span style='font-weight:300; color:rgb(254, 125, 1);'>doctor</span>
				</h2>
			</div>
			<div class='col-12'>
				<h1 class='jumbotron-fluid' style='color:#4a4a4a'>
					<h1 style='font-family:Roboto; font-weight:900; color:rgb(21, 31, 42);'>
						Use Terms
					</h1>
				</h1>
			</div>
		</div>
	</div>
</section>

<section class='py-4' style='background:#FFFFFF;'>
	<div class='container-fluid' 
			style='min-height:45vh; display:flex; flex-wrap:wrap; align-items:center; justify-content:center;'>
		<div class='col-12 col-sm-12 col-lg-6 pt-2'>
			<h6 class='pt-2' style='font-family:Montserrat,sans-serif; font-weight:900; color:#000000;'>
				Use Terms
			</h6>
			<ul>
				<li style='color:grey;'>
					All access of any area of https://www.whosedoctor.com (“the Website”) and the WhoseDoctor mobile application (“the App”) is governed by this Use Terms (“the Terms”).  
				</li>
				<li style='color:grey;'>
				 	In the Terms, the words "we", "our", and "us" refer to WhoseDoctor Pte Ltd.
				</li>

				<li style='color:grey;'>
					The overall purpose is to enable you seeking medical services to be matched with third party healthcare providers and delivery operators (collectively, the "Service"). 
				</li>

				<li style='color:grey;'>
					By using the Website and the App, you hereby expressly acknowledge and agree to be bound by the Terms, and any future amendments and additions to the Terms as published from time to time at http://www.whosedoctor.com or through the App.
				</li>

				<li style='color:grey;'>
					If you do not accept any of the Terms, please exit immediately. Continue only if you accept the Terms.
				</li>

				<li style='color:grey;'>
					We reserve the right to modify, vary and change the Terms and/or its policies relating to the Service at any time. Such modifications, variations and or changes to the Terms and/or its policies relating to the Service shall be effective upon the posting of an updated version at http://www.konnack.com. You agree that it shall be your responsibility to review the Terms regularly whereupon the continued use of the Service after any such changes, whether or not reviewed by you, shall constitute your consent and acceptance to such changes.
				</li>

				<li style='color:grey;'>
					We provide the Website and the App as Software as a Service only. 
				</li>

				<li style='color:grey;'>
					We are a technology company that do not provide medical and delivery services and we are not a healthcare provider nor are we a delivery operator. It is up to the third party healthcare providers and delivery operators to offer medical and delivery services to you and it is up to you to accept the medical and delivery services. 
				</li>

				<li style='color:grey;'>
					Our service is to connect you with third party healthcare providers and delivery operators, but is it not intended to provide medical services nor prescription delivery or any act that can be construed in any way as an act of a healthcare provider and/or delivery operator. We are not responsible nor liable for the acts and/or omission of any healthcare provider and delivery operator and/or any healthcare and/or delivery services provided to you.
				</li>

				<li style='color:grey;'>
					You agree to provide us with whatever proof of identity we may reasonably request or require.
				</li>

				<li style='color:grey;'>
					You agree to provide accurate, current and complete information as required for the Service and undertake the responsibility to maintain and update your information in a timely manner to keep it accurate, current and complete at all times during the term of this Agreement. 
				</li>

				<li style='color:grey;'>
					You agree that we may rely on your information as accurate, current and complete. 
				</li>

				<li style='color:grey;'>
					You agree that if your information is untrue, inaccurate, not current or incomplete in any respect, we have the right but not the obligation to terminate this Agreement and your use of the Service at any time with or without notice.
				</li>

				<li style='color:grey;'>
					You shall not employ any means to defraud us or enrich yourself, through any means, whether fraudulent or otherwise, through any event, promotion or campaign launched by us.
				</li>

				<li style='color:grey;'>
					You agree that the Service is provided on a reasonable effort basis.
				</li>

				<li style='color:grey;'>
					You agree that your use of the Service is also subject to our Privacy Policy and Refund Policy which may be amended from time to time.
				</li>

				<li style='color:grey;'>
					All disputes, controversies or differences (‘dispute’) arising out of or in connection with the Terms, including any questions regarding its existence, validity or termination, shall first be referred to mediation in Singapore, in accordance with the Law Society Mediation Rules for the time being in force.
				</li>
			</ul>

			<h6 class='pt-2' style='font-family:Montserrat,sans-serif; font-weight:900; color:#000000;'>
				Medical Disclaimer 
			</h6>
			<ul>
				<li style='color:grey;'>
					We are not involved in giving professional medical advice here. Before relying on the information on the Website or the App, you should do your own checks and obtain professional medical advice relevant to your particular circumstances. 
				</li>

				<li style='color:grey;'>
					The Website and the App may not cover all information available on a particular issue, and the information may not always be accurate, complete or up-to-date. 
				</li>

				<li style='color:grey;'>
					The information on the Website App and the Mobile App is not intended to be a substitute for the advice of a medical professional. 
				</li>

				<li style='color:grey;'>
					All information contained in the Website and the App is for informational purposes only and is to be used at your own risk. 
				</li>

				<li style='color:grey;'>
					We do not accept any responsibility for any reliance by you on the information contained in the Website or App.
				</li>
			</ul>
		</div>
	</div>
</section>
{% endblock %}

app/base/templates/navbar/_company_navbar.html
<nav class='navbar navbar-expand-sm'>
  <div class='container'>

    <!-- brand -->
    <a rel='noopener noreferrer' 
        href='{{ url_for("home.index") }}' class='navbar-brand mr-auto'>
      <h5 style='font-family:Montserrat,sans-serif; font-weight:900; color:rgb(21, 31, 42);'>
        whose<span style='font-weight:300; color:rgb(254, 125, 1)'>doctor</span>
      </h5>
    </a>

    <!-- navbar expand menu -->
    <ul class='navbar-nav ml-auto hide-div'>
      {% if current_user.is_anonymous %}
        <li class='nav-item'>
          <a rel='noopener noreferrer' 
              href='{{ url_for("auth.login") }}' class='nav-link btn-border'>
            Sign In
          </a>
        </li>
      {% else %}

        <li class='nav-item'>
          <a rel='noopener noreferrer' 
              href='{{ url_for("company.teleconsult_queue", company_id=company.id) }}' 
              class='nav-link'>
            Teleconsult
          </a>
        </li>
        <li class='nav-item'>
          <a rel='noopener noreferrer' 
              href='{{ url_for("company.shop", company_id=company.id) }}' class='nav-link'>
            Shop
          </a>
        </li>
        <li class='nav-item'>
          <a rel='noopener noreferrer' 
              href='{{ url_for("company.profile", company_id=company.id) }}' class='nav-link'>
            Co.Profile
          </a>
        </li>
        <li class='nav-item'>
          <a rel='noopener noreferrer' 
              href='{{ url_for("user.dashboard", user_id=current_user.id, username=current_user.username) }}' 
              class='nav-link'>
            Dashboard
          </a>
        </li>
        <li class='nav-item'>
          <a rel='noopener noreferrer' 
              href='{{ url_for("chat.chats") }}'class='nav-link'>
            Chats
            {% set new_chats = current_user.unread_chats() %}
            <span id='chat_count' class='badge badge-pill badge-secondary' 
                style='display: {% if new_chats %}inline-block {% else %}none {% endif %};'>
              {{ session['CHAT'] }}
            </span>
          </a>
        </li>
        <li class='nav-item'>
          <a rel='noopener noreferrer' 
              href='{{ url_for("order.dashboard", user_id=current_user.id) }}' class='nav-link'>
            <span class='fa-stack-mod'>
              <i class='fa fa-first-order  fa-stack-1x text-grey'></i>
            </span>
            
            <span id='' class='badge badge-pill badge-secondary'
                style='display: {% if session["ORDERS"] != 0 %}inline-block {% else %}none {% endif %};'>
              {{ session['ORDERS']  }}
            </span>
          </a>
        </li>
        <li class='nav-item'>
          <a rel='noopener noreferrer' 
          href='{{ url_for("auth.logout") }}' class='nav-link btn-border'>
            Sign Out
          </a>
        </li>
      {% endif %}
    </ul>
    
    <!-- toggle -->
    <button class='navbar-toggler custom-toggler'>
      <span class='navbar-toggler-icon' data-toggle='collapse' data-target='#navbarMenu'></span>
    </button>
    
    <!-- navbar collapse menu -->
    <div id='navbarMenu' class='collapse navbar-toggleable-sm'>
      <ul class='navbar-nav ml-auto'>
        {% if current_user.is_anonymous %}
          <li class='nav-item'>
            <a rel='noopener noreferrer' 
                href='{{ url_for("auth.login") }}' class='nav-link btn-border'>
                <span class='fa-stack'>
                  <i class='fa fa-sign-in fa-stack-1x text-grey'></i>
                </span>
              Sign In
            </a>
          </li>
        {% else %}

          <li class='nav-item'>
            <a rel='noopener noreferrer' 
                href='{{ url_for("company.teleconsult_queue", company_id=company.id) }}' 
                class='nav-link'>
              <span class='fa-stack'>
                <i class='fa fa-id-card-o  fa-stack-1x text-grey'></i>
              </span>
              Teleconsult
            </a>
          </li>
          <li class='nav-item'>
            <a rel='noopener noreferrer' 
                href='{{ url_for("company.shop", company_id=company.id) }}' class='nav-link'>
              <span class='fa-stack'>
                <i class='fa fa-id-card-o  fa-stack-1x text-grey'></i>
              </span>
              shop
            </a>
          </li>
          <li class='nav-item'>
            <a rel='noopener noreferrer' 
                href='{{ url_for("chat.chats") }}'class='nav-link'>
              <span class='fa-stack'>
                <i class='fa fa-comments fa-stack-1x text-grey'></i>
              </span>
              Chats
              {% set new_chats = current_user.unread_chats() %}
              <span id='chat_count' class='badge badge-pill badge-secondary' 
                  style='display: {% if new_chats %}inline-block {% else %}none {% endif %};'>
                {{ new_chats }}
              </span>
            </a>
          </li>
          <li class='nav-item'>
            <a rel='noopener noreferrer' 
                href='{{ url_for("order.dashboard", user_id=current_user.id) }}' class='nav-link'>
              <span class='fa-stack'>
                <i class='fa fa-first-order  fa-stack-1x text-grey'></i>
              </span>
              Order
              <span id='' class='badge badge-pill badge-secondary'
                  style='display: {% if session["ORDERS"] != 0 %}inline-block {% else %}none {% endif %};'>
                {{ session['ORDERS']  }}
              </span>
            </a>
          </li>
          <li class='nav-item'>
            <a rel='noopener noreferrer' 
                href='{{ url_for("auth.logout") }}' class='nav-link btn-border'>
              <span class='fa-stack'>
                <i class='fa fa-sign-out fa-stack-1x text-grey'></i>
              </span>
              Sign Out
            </a>
          </li>
        {% endif %}
      </ul>
    </div>
    
  </div>
</nav>

app/base/templates/sidebar/_admin_sidebar.html
<div class='sidenav py-4' style='display:flex; flex-wrap:wrap; align-items:center;'>
  <div class='container' style='width:100%;'>
    <a rel='noopener noreferrer' 
        href='{{ url_for("admin.booking") }}' class='nav-link'>
      <span class='fa-stack'>
        <i class='fa fa-truck fa-stack-1x text-grey'></i>
      </span>
      <small>Bookings</small>
    </a>
    <a rel='noopener noreferrer' 
        href='{{ url_for("admin.cart") }}' class='nav-link'>
      <span class='fa-stack'>
        <i class='fa fa-shopping-cart fa-stack-1x text-grey'></i>
      </span>
      <small>Carts</small>
    </a>
    <a rel='noopener noreferrer' 
        href='{{ url_for("admin.company") }}' class='nav-link'>
      <span class='fa-stack'>
        <i class='fa fa-building fa-stack-1x text-grey'></i>
      </span>
      <small>Companies</small>
    </a>
    <a rel='noopener noreferrer' 
        href='{{ url_for("admin.consultation") }}' class='nav-link'>
      <span class='fa-stack'>
        <i class='fa fa-universal-access fa-stack-1x text-grey'></i>
      </span>
      <small>Consultations</small>
    </a>
    <a rel='noopener noreferrer' 
        href='{{ url_for("admin.currency") }}' class='nav-link'>
      <span class='fa-stack'>
        <i class='fa fa-money fa-stack-1x text-grey'></i>
      </span>
      <small>Currencies</small>
    </a>
    <a rel='noopener noreferrer' 
        href='{{ url_for("admin.delivery") }}' class='nav-link'>
      <span class='fa-stack'>
        <i class='fa fa-truck fa-stack-1x text-grey'></i>
      </span>
      <small>Delivery Jobs</small>
    </a>
    <a rel='noopener noreferrer' 
        href='{{ url_for("admin.doctor") }}' class='nav-link'>
      <span class='fa-stack'>
        <i class='fa fa-user-md fa-stack-1x text-grey'></i>
      </span>
      <small>Doctors</small>
    </a>
    <a rel='noopener noreferrer' 
        href='{{ url_for("admin.feedback") }}' class='nav-link'>
      <span class='fa-stack'>
        <i class='fa fa-comments-o  fa-stack-1x text-grey'></i>
      </span>
      <small>Feedbacks</small>
    </a>
    <a rel='noopener noreferrer' 
        href='{{ url_for("admin.health_record") }}' class='nav-link'>
      <span class='fa-stack'>
        <i class='fa fa-comments-o  fa-stack-1x text-grey'></i>
      </span>
      <small>Health Records</small>
    </a>
    <a rel='noopener noreferrer' 
        href='{{ url_for("admin.medical_cert") }}' class='nav-link'>
      <span class='fa-stack'>
        <i class='fa fa fa-certificate fa-stack-1x text-grey'></i>
      </span>
      <small>Medical Certs</small>
    </a>
    <a rel='noopener noreferrer' 
        href='{{ url_for("admin.order") }}' class='nav-link'>
      <span class='fa-stack'>
        <i class='fa fa-first-order fa-stack-1x text-grey'></i>
      </span>
      <small>Orders</small>
    </a>
    <a rel='noopener noreferrer' 
        href='{{ url_for("admin.people") }}' class='nav-link'>
      <span class='fa-stack'>
        <i class='fa fa-users fa-stack-1x text-grey'></i>
      </span>
      <small>People</small>
    </a>
    <a rel='noopener noreferrer' 
        href='{{ url_for("admin.product") }}' class='nav-link'>
      <span class='fa-stack'>
        <i class='fa fa-shopping-bag fa-stack-1x text-grey'></i>
      </span>
      <small>Products</small>
    </a>
    <a rel='noopener noreferrer' 
        href='{{ url_for("admin.receipt") }}' class='nav-link'>
      <span class='fa-stack'>
        <i class='fa fa-truck fa-stack-1x text-grey'></i>
      </span>
      <small>Receipts</small>
    </a>

    <hr style='border-top:1px dotted grey;'>

    <a rel='noopener noreferrer' 
        href='{{ url_for("geomap.show") }}' class='nav-link'>
      <span class='fa-stack'>
        <i class='fa fa-map fa-stack-1x text-grey'></i>
      </span>
      <small>GeoMap</small>
    </a>
  </div>
</div>