app/cart/models.py
from app import db


class Cart(db.Model):
	__tablename__ = 'cart'
	id = db.Column(db.Integer, primary_key=True)
	user_id = db.Column(db.Integer, db.ForeignKey('user.id'))
	cart_items = db.relationship('CartItem', 
		foreign_keys='CartItem.cart_id', backref='cart', lazy='dynamic')
	# 'owner' property defined in User.cart via backref.

	def __repr__(self):
		return '<Cart {}>'.format(self.user_id)

	def get_currency(self):
		for cart_item in self.cart_items:
			if any(cart_item.currency for cart_item in self.cart_items):
				currency = cart_item.currency
				return currency

	def count_total_items(self):
		total_items = 0
		for cart_item in self.cart_items:
			total_items = sum(cart_item.quantity for cart_item in self.cart_items)
		return total_items

	def count_total_amount(self):
		total_amount = 0
		for cart_item in self.cart_items:
			total_amount = sum(cart_item.ttl_amount for cart_item in self.cart_items)
			return total_amount


class CartItem(db.Model):
	__tablename__ = 'cart_item'
	id = db.Column(db.Integer, primary_key=True)
	product_id = db.Column(db.Integer, db.ForeignKey('product.id'))
	product = db.relationship('Product', backref=db.backref('cart_item', uselist=False))
	supplier_id = db.Column(db.Integer, db.ForeignKey('company.id'))
	brand = db.Column(db.String(64), index=True)
	model = db.Column(db.String(128), index=True)
	currency = db.Column(db.String(128))
	amount = db.Column(db.Integer())
	discount = db.Column(db.Integer())
	quantity = db.Column(db.Integer)
	ttl_amount = db.Column(db.Integer())
	feature_picture = db.Column(db.String(64), nullable=True, default='default.jpeg')
	cart_id = db.Column(db.Integer, db.ForeignKey('cart.id'))
	order_id = db.Column(db.Integer, db.ForeignKey('order.id'))
	incoming_order_id = db.Column(db.Integer, db.ForeignKey('incoming_order.id'))
	# 'cart' property defined in Cart.cart_items via backref.
	# 'order' property defined in Order.cart_items via backref.
	# 'supplier' property defined in Company.cart_items via backref.

	def __repr__(self):
		return '<CartItem {}>'.format(self.product_id)

app/cart/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SelectField, SubmitField
from wtforms.validators import DataRequired

from app.cart.models import Cart
from app.user.models import User


class CartForm(FlaskForm): 
    product = StringField('Product', validators=[DataRequired()])
    submit = SubmitField('Checkout')

app/cart/__init__.py
from flask import Blueprint

cart_blueprint = Blueprint('cart', __name__, template_folder='templates')

from app.cart import routes, models

app/cart/routes.py
import os
import stripe
import functools

from flask import flash, render_template, request, redirect, url_for, session, jsonify, abort
from flask_login import current_user, login_required
from sqlalchemy.orm import aliased
from flask_socketio import SocketIO, send, emit
from .. import socketio

from app import db
from app.cart import cart_blueprint
from app.cart.models import Cart, CartItem
from app.order.models import Order
from app.user.models import User
from app.company.models import Company
from app.product.models import Product


stripe.api_key = os.environ.get('STRIPE_SECRET_KEY')
checkout_public_key = os.environ.get('STRIPE_PUBLIC_KEY')
endpoint_secret = os.environ.get('STRIPE_END_POINT_SECRET')


def check_superadmin():
    if not current_user.is_superadmin:
        abort(403)


@cart_blueprint.route('/create_cart/user/<int:user_id>', methods=['GET', 'POST'])
@login_required
def create(user_id):
    user = User.query.get_or_404(current_user.id)
    if request.method == 'POST':
        if cart == '':
            cart = Cart(id=current_user.id, user_id=current_user.id)
            db.session.add(cart)
            db.session.commit()
            flash('Shopping cart created.')
            return redirect(url_for('cart.dashboard', user=user))


@cart_blueprint.route('/dashboard/<int:cart_id>', methods=['GET', 'POST'])
@login_required
def dashboard(cart_id):
    user = User.query.get_or_404(current_user.id)
    cart = Cart.query.get_or_404(cart_id)
    currency = cart.get_currency()
    total_items = cart.count_total_items()
    total_amount = cart.count_total_amount()

    session['CART'] = cart.count_total_items()
    print('Session Cart Items: ' + str(session['CART']))

    orders = Order.query.join(Order.buyer).filter(User.id==user.id)
    session['ORDER'] = orders.count()
    
    return render_template('cart/dashboard.html', 
        title='Cart', 
        user=user, 
        cart=cart,
        currency=currency, 
        total_items=total_items, 
        total_amount=total_amount, 
        orders = orders, 
        checkout_public_key=checkout_public_key)


@cart_blueprint.route('/delete_cart/<int:cart_id>/<int:user_id>', methods=['GET', 'POST'])
@login_required
def delete(cart_id, user_id):
    check_superadmin()
    cart = Cart.query.get_or_404(cart_id)
    user_id = cart_id
    db.session.delete(cart)
    db.session.commit()
    return redirect(url_for('admin.cart'))


@cart_blueprint.route('/add_item/<int:product_id>', methods=['GET', 'POST'])
@login_required
def add_item(product_id):
    product = Product.query.get_or_404(product_id)

    company_id = product.company_id
    supplier = Company.query.get_or_404(company_id)

    cart_id = current_user.id
    cart = Cart.query.get(int(cart_id))
    
    if any(product.id==cart_item.product_id for cart_item in cart.cart_items):
        cart_item = CartItem.query.filter(CartItem.product_id==product_id).\
                                    join(CartItem.cart).\
                                    filter(Cart.id==cart_id).first()
        print(f'CartItem ID: {cart_item.id} instantiated')
        
        cart_item.quantity += 1
        quantity = cart_item.quantity
        print(f'CartItem ID: {cart_item.id} quantity incremented')

        #Calculations for total amount of each item
        cart_item.ttl_amount = (quantity * cart_item.amount)
        ttl_amount = cart_item.ttl_amount
        print(f'CartItem ID: {cart_item.id} ttl_amount incremented')

        cart_item = CartItem(id=cart_item.id, quantity=quantity, ttl_amount=ttl_amount)
        print(f'CartItem ID: {cart_item.id} updating')
        db.session.commit()

        print(f'CartItem ID: {cart_item.id} committed')
        flash(f'CartItem ID: {cart_item.id} is in the cart. Quantity and total amount adjusted.')
    else:
        ttl_amount = product.amount

        cart_item = CartItem(product_id=product.id, 
                            supplier=supplier, 
                            brand=product.brand, 
                            model=product.model, 
                            currency=product.currency, 
                            amount=product.amount, 
                            quantity=1, 
                            ttl_amount=ttl_amount, 
                            feature_picture=product.feature_picture, 
                            cart_id=cart_id)
        db.session.add(cart_item)
        cart.cart_items.append(cart_item)
        db.session.commit()
        flash(f'CartItem ID: {cart_item.id} added to cart')
    return redirect(url_for('product.profile', product_id=product.id, cart_id=cart_id, cart=cart, cart_item=cart_item))


@cart_blueprint.route('/remove_item/<int:cart_item_id>', methods=['GET', 'POST'])
@login_required
def remove_item(cart_item_id):
    #cart_id = current_user.id
    cart_item = CartItem.query.get_or_404(cart_item_id)
    cart_id = cart_item.cart_id
    cart = Cart.query.get(int(cart_id))
    cart.cart_items.remove(cart_item)
    db.session.commit()
    print(f'CartItem ID: {cart_item.id} removed from cart')
    flash(f'CartItem ID: {cart_item.id} removed from cart')
    return redirect(url_for('cart.dashboard', cart_id=cart_id, cart=cart, cart_item=cart_item))

app/cart/templates/cart/dashboard.html
{% extends 'base/layout.html' %}


{% block content %}
<div style='min-height:80vh; display:flex; align-items:center; justify-content:center;'>
	<div class='container' style='min-height:80vh; padding:0;'>
		
			<div class='hide-div py-4'
					style='display:flex; flex-wrap:wrap; align-items:center; justify-content:center;'><!-- CONTENT 1 -->
				<div class='container-fluid'>
					<nav>
						<div class='nav nav-tabs' id='nav-tab' role='tablist'>
							<a class='nav-item nav-link active' id='nav-current-tab' data-toggle='tab' href='#nav-current' 
									role='tab' aria-controls='nav-current' aria-selected='true'>
								Cart
							</a>
							<a class='nav-item nav-link' id='nav-history-tab' data-toggle='tab' href='#nav-history' 
									role='tab' aria-controls='nav-history' aria-selected='false'>
								History
							</a>
						</div>
					</nav>

					<div class='tab-content' id='nav-tabContent'><!-- Tab Contents -->

						<div class='tab-pane fade show active' id='nav-current' role='tabpanel' 
								aria-labelledby='nav-current-tab'><!-- Current -->
							<div class='hide-div pb-4'
									style='display:flex; flex-wrap:wrap; align-items:center; justify-content:center;'>
								{% if cart.cart_items | list |length ==0 %} <!-- Cart -->		
									<div style='min-height:60vh; display:flex; align-items:center; justify-content:center;'>
										<div class='jumbotron-fluid text-center'>
											<h2 style='font-family:Georgia, serif; color:#4a4a4a; line-height:1.5;'><strong>
												Did you forget to add an item or three?
											</strong></h2>
											<h3 style='font-family:Verdana, sans-serif; line-height:1.5; color:#7d7d7d; font-weight:300;'>
												Empty Cart
											</h3>
										</div>
									</div>
								{% else %}
									<div class='container' 
											style='min-height:25vh; display:flex; align-items:center; justify-content:center;'>
										<table class='table table-sm table-borderless table-hover' style='width:100%;'>
											<tbody>
											{% for cart_item in cart.cart_items %}
												<tr style='text-align:left;'>
													<td style='width:10%; vertical-align:middle;'>
														<!-- src='{{ url_for("product.get_featured", filename=cart_item.feature_picture) }}' -->
														<img src='{{ url_for("static", filename="uploads/product_img/" + cart_item.feature_picture) }}'
															style='height:40px; width:40px; margin-left:-4px; object-fit:cover; object-position:center center; 
																box-shadow:0 0 0 1px #FFF; border-radius:9999px'>
													</td>
													<td style='width:60%; vertical-align:middle;'>
														<Small>ID:{{ cart_item.id }} {{ cart_item.model }}</Small>
														<small class='hide-div'>{{ cart_item.brand }}</small>
														<!-- format amount() defined in __init__.py file -->
														<small class='hide-div'>{{ cart_item.currency }} {{ cart_item.amount | format_amount }}</small> 
														<br>
														<small class='hide-div'>
															Supplier ID: {{ cart_item.product.supplier.id }} | Supplier: {{ cart_item.product.supplier.name }} 
														</small>
													</td>
													<td class='hide-div' style='width:5%; vertical-align:middle;'>
														<small>{{ cart_item.quantity }} unit</small>
													</td>
													<td class='hide-div' style='width:20%; vertical-align:middle;'>
														<!-- format amount() defined in __init__.py file -->
														<small>{{ cart_item.currency }}</small> {{ cart_item.ttl_amount | format_amount }}
													</td>
													<td style='width:5%; vertical-align:middle;'>
														<a href='{{ url_for("cart.remove_item", cart_item_id=cart_item.id) }}' class=''>
															<span class="fa-stack">
																<i class="fa fa-trash-o fa-stack-1x"></i>
															</span>
														</a>
													</td>
												</tr>
											{% endfor %}
											</tbody>
										</table>
									</div>
									<div class='py-4' 
											style='display:flex; flex-wrap:wrap; align-items:center; justify-content:center;'>
										<div class='container text-center hide-div' style='width:360px;'>	
											<span style='font-family:Roboto, sans-serif; color:#555; font-size:30px;'>
												{{ cart.cart_items | list | length }}
											</span>
											<p style='color:#555;'>Products</p>
										</div>
										<div class='container text-center hide-div' style='width:360px;'>	
											<span style='font-family:Roboto, sans-serif; color:#555; font-size:30px;'> {{ total_items }}</span>
											<p style='color:#555;'>Items</p>
										</div>
										<div class='container text-center pb-4' style='width:360px;'>	
											<small style='font-family:Roboto, sans-serif; color:#555;'>{{ currency }}</small>
											<span style='font-family:Roboto, sans-serif; color:#555; font-size:30px;'>
											 {{ total_amount | format_amount }}
											</span>
										</div>
										<div class='container text-center' style='width:260px;'>	
											{% if user == current_user %}
												<button id='checkout-button' class='btn btn-secondary btn-lg'>Checkout</button>
											{% endif %}
										</div>
									</div>
								{% endif %}
								<div class='container text-center' style='margin-top:40px;'>
									<small class='text-muted'>
										Current User: {{ current_user.username }} | Cart Owner: {{ cart.owner.username }} | Cart ID:{{ cart.user_id }} | 
										Cart: {{ user.cart }}
									</small>
								</div><!-- End Cart -->
							</div>
						</div><!-- End Current -->

						<div class='tab-pane fade' id='nav-history' role='tabpanel' aria-labelledby='nav-history-tab'><!-- History -->
							<div class='hide-div py-4 appointment-items'
									style='display:flex; flex-wrap:wrap; align-items:center; justify-content:center;'>
								<div class='container' 
										style='min-height:25vh; display:flex; align-items:flex-start; justify-content:center;'><!-- Incoming Orders -->
									<table class='table table-sm table-borderless table-hover'>
										<tbody>
										{% for order in orders %}
											<tr style='text-align:left;'>
												<td style='width:20%; vertical-align:middle;'>
													<Small>Order ID:{{ order.id }}</Small>
													<br>
													<span style='color:grey; font-size:0.5em;'>
														<span class='hide-div'>
															created on: {{ order.created_on.strftime('%a, %d-%b-%Y, %H:%M') }}
														</span>
														({{ order.created_on | datetimeformat }})
													</span>
												</td>

												<td style='width:40%; vertical-align:middle;'>
													{% for cart_item in order.cart_items %}
														{{ cart_item.brand }} <span style='color:grey; font-size:0.5em;'>
														from {{ cart_item.supplier.name }}</span><br>
													{% endfor %}
												</td>

												<td style='width:20%; vertical-align:middle;'>
													{% for cart_item in order.cart_items %}
														<small style='font-family:Roboto, sans-serif; color:#555;'>{{ cart_item.currency }}</small>
														{{ cart_item.ttl_amount | format_amount }}
													{% endfor %}
												</td>

												<td class='hide-div' style='width:20%; vertical-align:middle;'>
													<small>Purchased By: {{ order.buyer.username }}</small>
												</td>
											</tr>
										{% endfor %}

										<!-- customer receipt generated from booking.create route  -->
										{% for receipt in current_user.customer_receipts %} <!-- Customer Receipt -->
											<tr style='text-align:left;'>
												<td style='vertical-align:middle;'>
													<Small>Receipt ID:{{ receipt.id }}</Small>
													<br>
													<span style='color:grey; font-size:0.5em;'>
														<span class='hide-div'>
															created on: {{ receipt.created_on.strftime('%a, %d-%b-%Y, %H:%M') }}
														</span>
														({{ receipt.created_on | datetimeformat }})
													</span>
												</td>
												<td style='vertical-align:middle;'>
													{{ receipt.description }}
												</td>
												<td style='vertical-align:middle;'>
													Paid: S$ {{ receipt.customer_paid_amount | format_amount }}
												</td>
												<td class='hide-div' style='vertical-align:middle;'>
													<a rel='noopener noreferrer' 
															href='{{ url_for("receipt.delete", receipt_id=receipt.id) }}' style='color:#000000;'>
														<span class="fa-stack">
															<i class="fa fa-trash-o fa-stack-1x"></i>
														</span>
													</a>
												</td>
											</tr>
										{% endfor %}<!-- End Customer Receipt -->

										<!-- provider receipt generated from precription.create route  -->
										{% if current_user.profession == 'Physician' %}<!-- Provider Receipt -->
											{% for receipt in current_user.provider_receipts %} 
												<tr style='text-align:left;'>
													<td style='vertical-align:middle;'>
														<Small>Receipt ID:{{ receipt.id }}</Small>
														<br>
														<span style='color:grey; font-size:0.5em;'>
															<span class='hide-div'>
																created on: {{ receipt.created_on.strftime('%a, %d-%b-%Y, %H:%M') }}
															</span>
															({{ receipt.created_on | datetimeformat }})
														</span>
													</td>
													<td style='vertical-align:middle;'>
														{{ receipt.description }}
													</td>
													<td style='vertical-align:middle;'>
														Receiving: S$ {{ receipt.provider_received_amount | format_amount }}
													</td>
													<td class='hide-div' style='vertical-align:middle;'>
														<a rel='noopener noreferrer' 
																href='{{ url_for("receipt.delete", receipt_id=receipt.id) }}' style='color:#000000;'>
															<span class="fa-stack">
																<i class="fa fa-trash-o fa-stack-1x"></i>
															</span>
														</a>
													</td>
												</tr>
											{% endfor %}
										{% endif %}<!-- End Provider Receipt -->
										</tbody>
									</table>
								</div><!-- End Incoming Orders -->
							</div>
						</div><!-- End History -->

					</div><!-- End Tab Contents -->

				</div>
			</div><!-- End CONTENT 1 -->

	</div>
</div>
{% endblock %}


{% block scripts %}
	{{ super() }}
	<script src='https://js.stripe.com/v3/'></script>
	<script src='{{ url_for("static", filename="javascripts/stripe-ajax.js") }}'></script>
{% endblock %}